
server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersecurity
    username: root
    password: gaurav
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
